language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: 
  - python setup.py install

script: 
  - python -c "from poloniex import Poloniex;Poloniex().marketTicker()"
